/**
 * Focused compatibility checks for security-driven dependency overrides.
 *
 * @jest-environment node
 */

describe('security dependency compatibility', () => {
  it('keeps Workflow core serialization and identifier dependencies compatible at patched versions', async () => {
    const { spawnSync } = require('node:child_process');
    const script = `
      (async () => {
        const fs = require('node:fs');
        const path = require('node:path');
        const { createRequire } = require('node:module');
        const { pathToFileURL } = require('node:url');
        const coreEntry = require.resolve('@workflow/core');
        const coreRequire = createRequire(coreEntry);
        const devaluePath = coreRequire.resolve('devalue');
        const nanoidPath = coreRequire.resolve('nanoid');
        const version = (file) => JSON.parse(fs.readFileSync(
          path.join(path.dirname(file), 'package.json'), 'utf8',
        )).version;
        const {
          dehydrateRunError,
          hydrateRunError,
          encodeWithFormatPrefix,
          SerializationFormat,
        } = await import(
          pathToFileURL(path.join(path.dirname(coreEntry), 'serialization.js')).href,
        );
        const value = { id: 'workflow-step', values: [1, 'two'] };
        const encoded = await dehydrateRunError(value, 'compatibility-test', undefined);
        const decoded = await hydrateRunError(encoded, 'compatibility-test', undefined);
        // Generated by devalue 5.9.2 in an isolated install; preserve this old wire form.
        const legacyPayload = '[{"createdAt":1,"first":2,"second":2},["Date","2026-09-30T12:34:56.000Z"],{"label":3},"persisted"]';
        const legacyBytes = encodeWithFormatPrefix(
          SerializationFormat.DEVALUE_V1,
          new TextEncoder().encode(legacyPayload),
        );
        const legacy = await hydrateRunError(legacyBytes, 'compatibility-test', undefined);
        const { nanoid } = await import(pathToFileURL(nanoidPath).href);
        process.stdout.write(JSON.stringify({
          devalue: version(devaluePath),
          nanoid: version(nanoidPath),
          decoded,
          legacy: {
            createdAt: legacy.createdAt.toISOString(),
            first: legacy.first.label,
            sharedReference: legacy.first === legacy.second,
          },
          generatedId: nanoid(),
        }));
      })().catch((error) => { console.error(error); process.exitCode = 1; });
    `;
    const result = spawnSync(process.execPath, ['-e', script], { encoding: 'utf8', timeout: 5_000 });

    expect(result.error).toBeUndefined();
    expect(result.status).toBe(0);
    const outcome = JSON.parse(result.stdout);
    expect(outcome.devalue).toBe('5.9.3');
    expect(outcome.nanoid).toBe('5.1.16');
    expect(outcome.decoded).toEqual({ id: 'workflow-step', values: [1, 'two'] });
    expect(outcome.legacy).toEqual({
      createdAt: '2026-09-30T12:34:56.000Z',
      first: 'persisted',
      sharedReference: true,
    });
    expect(outcome.generatedId).toMatch(/^[A-Za-z0-9_-]{21}$/);
  });

  it('rejects serialization of Uint8Array views backed by shared memory', () => {
    const { spawnSync } = require('node:child_process');
    const script = `
      (async () => {
        const { createRequire } = require('node:module');
        const { pathToFileURL } = require('node:url');
        const coreRequire = createRequire(require.resolve('@workflow/core'));
        const { stringify } = await import(pathToFileURL(coreRequire.resolve('devalue')).href);
        try {
          stringify(new Uint8Array(new SharedArrayBuffer(16)));
          process.exitCode = 2;
        } catch (error) {
          process.stdout.write(error.name);
        }
      })().catch((error) => { console.error(error); process.exitCode = 1; });
    `;
    const result = spawnSync(process.execPath, ['-e', script], { encoding: 'utf8', timeout: 2_000 });

    expect(result.error).toBeUndefined();
    expect(result.status).toBe(0);
    expect(result.stdout).toBe('DevalueError');
  });

  it('does not hang on negative-size IDs in Workflow core nanoid/non-secure', () => {
    const { spawnSync } = require('node:child_process');
    const script = `
      const { createRequire } = require('node:module');
      const { pathToFileURL } = require('node:url');
      const coreRequire = createRequire(require.resolve('@workflow/core'));
      import(pathToFileURL(coreRequire.resolve('nanoid/non-secure')).href).then(({ nanoid }) => {
        process.stdout.write(String(nanoid(-1).length));
      }).catch((error) => {
        process.stderr.write(error.message);
        process.exitCode = 1;
      });
    `;
    const result = spawnSync(process.execPath, ['-e', script], { encoding: 'utf8', timeout: 2_000 });

    expect(result.error).toBeUndefined();
    expect(result.status).toBe(0);
    expect(result.stdout).toBe('0');
  });

  it('preserves the honorarium UUID-v5 identity contract with the real uuid package', async () => {
    const { v5: uuidv5 } = await import('uuid');
    const namespace = 'b1d9f0c2-4a3e-5c6d-8e7f-0a1b2c3d4e5f';

    expect(uuidv5('sug-1111', namespace)).toBe('ff022dc4-f4cf-535b-a697-05ae01730958');
  });

  it('keeps ExcelJS conditional-format UUID generation working', async () => {
    const ExcelJS = require('exceljs');
    const workbook = new ExcelJS.Workbook();
    const sheet = workbook.addWorksheet('Compatibility');
    sheet.getCell('A1').value = 1;
    sheet.addConditionalFormatting({
      ref: 'A1',
      rules: [{
        type: 'expression',
        formulae: ['A1>0'],
        style: { font: { bold: true } },
      }],
    });

    const bytes = await workbook.xlsx.writeBuffer();
    const roundTripped = new ExcelJS.Workbook();
    await roundTripped.xlsx.load(bytes);

    expect(roundTripped.getWorksheet('Compatibility').conditionalFormattings).toHaveLength(1);
  });

  it('provides both brace-expansion APIs and bounds exploit-class output length', () => {
    const legacyExpand = require('brace-expansion');
    const chainedGroups = '{a,b}'.repeat(100);
    const pathologicalDepth = '{a,b}'.repeat(1_500);
    const options = { max: 1_000, maxLength: 1_000 };

    expect(typeof legacyExpand).toBe('function');
    expect(legacyExpand('{a,b}')).toEqual(['a', 'b']);
    expect(legacyExpand.expand('{1..2}')).toEqual(['1', '2']);

    const bounded = legacyExpand(chainedGroups, options);
    const totalLength = bounded.reduce((sum, value) => sum + value.length, 0);
    expect(totalLength).toBeLessThanOrEqual(options.maxLength);
    expect(legacyExpand(pathologicalDepth)).toEqual([pathologicalDepth]);
  });
});
